update git hooks

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,8 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-pnpm check-lint
+echo "Checking Code Lint"
+pnpm check-lint || {
+  echo "Code Lint Check Failed"
+  false
+}
